version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    restart: unless-stopped 